# Generated by Django 5.2 on 2025-04-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_picture',
            new_name='pp',
        ),
    ]
