# Generated by Django 5.2 on 2025-04-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_profile_picture_user_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pp',
            field=models.ImageField(blank=True, null=True, upload_to='prof_pics/'),
        ),
    ]
